### ISSUE TITLE
你好 想请教一下操作程序

### ISSUE THREAD

**Issue by Ppinnacle** [zjrandom951/douyin_comments#1]
![image](https://user-images.githubusercontent.com/95207807/222673496-f534399e-0c7d-40d9-9ed4-e88f5524f29c.png)

按.md说明，只修改了用户链接参数，webdriver也是匹配的，但是拉起来以后只是在主页自动下滑，然后就报如图片所示的错误了。所以想请教一下这个具体是怎么用的，谢谢了！

**Comment by zjrandom951** [comment]
你好，该程序为demo，没有做过多的容错处理，这种情况可能是程序取到了空的评论字符串，您可以调试一下看看是不是，尝试修改程序使得评论为空时也能继续运行

**Comment by Ppinnacle** [comment]
T-T关键我是个小白，没啥编程知识，就是想问问您在获取数据时是按什么顺序来操作的，这个报错大概率就是我的操作问题。

**Comment by zjrandom951** [comment]
正常需要在文件目录下直接运行，然后会弹出个人主页，需要让网页正常显示，遇到弹窗就关掉，遇到滑块要手动验证，保证界面自动滑动就可以爬取了

**Comment by Ppinnacle** [comment]
![image](https://user-images.githubusercontent.com/95207807/222677670-3a983be8-b457-441d-8b63-db2c58ba62c7.png)

代码成功跑起来了，感谢！！！

**Comment by zjrandom951** [comment]
You're welcome

**Comment by guapi369** [comment]
请求小白的话可以学吗，好多不懂的

**Comment by zjrandom951** [comment]
可以
