### ISSUE TITLE
貌似有一个bug

### ISSUE THREAD

**Issue by Ppinnacle** [zjrandom951/douyin_comments#2]
![image](https://user-images.githubusercontent.com/95207807/223047635-6042596f-dbc0-4bf4-8fcb-6b182bb21d04.png)

具体表现为无限制地下拉视频，直到最底，然后报错。

**Comment by zjrandom951** [comment]
抖音主页的元素排布发生了变化，正在修改代码

**Comment by zjrandom951** [comment]
再看一看，应该解决了

**Comment by Ppinnacle** [comment]
感谢开源~跑了一下已经没有问题了，想问一下maxnum参数设置成10*是有什么讲究嘛？

**Comment by zjrandom951** [comment]
不一定要10*，只是为了设置一个翻取评论数量或者视频数量的最大值，后续的评论多数点赞数少，限制爬取的数量可以缩小程序运行时间
